apiVersion: v2
name: common-document-generation-service
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
kubeVersion: ">= 1.13.0"
description: A microservice for merging JSON data into xml-based templates (powered by Carbone.io)
# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
keywords:
  - nodejs
  - javascript
  - docker
  - microservice
  - document-generation
  - templating
  - cdogs
home: https://github.com/bcgov/common-document-generation-service
sources:
  - https://github.com/bcgov/common-document-generation-service
dependencies: []
maintainers:
  - name: NR Common Service Showcase Team
    email: NR.CommonServiceShowcase@gov.bc.ca
    url: https://bcgov.github.io/common-service-showcase/team.html
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.4.2"
deprecated: false
annotations: {}
