services:
  carbone:
    image: carbone/carbone-ee:full-fonts
    ports:
      - "4000:4000"
    secrets:
      - source: carbone-license
        target: /app/config/prod.carbone-license
    volumes:
      - ./template:/app/template
      - ./render:/app/render

secrets:
  carbone-license:
    file: ./carbone-license.txt
