---
config:
  enabled: true
  configMap:
    KC_ENABLED: "true"
    KC_PUBLICKEY: ~
    KC_REALM: comsvcauth
    KC_SERVERURL: "https://test.loginproxy.gov.bc.ca/auth"

    SERVER_BODYLIMIT: 100mb
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"

    CACHE_DIR: "/tmp/carbone-files"
    CACHE_SIZE: 2GB
    CONVERTER_FACTORY_TIMEOUT: "60000"
    START_CARBONE: "true"
    UPLOAD_FIELD_NAME: template
    UPLOAD_FILE_COUNT: "1"
    UPLOAD_FILE_SIZE: 25MB
