---
features:
  authentication: true

config:
  enabled: true
  releaseScoped: true

persistentVolumeClaim:
  enabled: false

cronJob:
  enabled: false

fluentBit:
  enabled: false

carbone:
  enabled: true
  releaseScoped: true
