---
features:
  authentication: true

config:
  enabled: true
  configMap:
    KC_ENABLED: "true"
    KC_PUBLICKEY: >-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtq5+xTKB1FRCwufdluEx8mNIZU3eXpo91QUrqlpq226HcyF9WPihdpuZzdlS+kW6EC2prZfJpvDvzT/Og4fx9ZoQVKV0uYvWvEg5Sc3ikQMfO0ngqUC6FkxElj9LzpijpdEQd0JAmmem2329lITwWroX70imLhYu3aY+Q3hSY2lg5OJCBw0I2pulfQiMsGn3vgkwSvmIsDhOgSnwPJhPxD9TY6kjvTff6LB1bFSwlxh1l8dRBqRabDunoHn/uHfhVAHB/SgPkvP5Ybc5bP/idBNP0kiQcWiT02Z7aB1r7Fnd5YH9FEDhhF5OIYYBzHP4hPm6AgqG/IDhAuiqf/F9eQIDAQAB
    KC_REALM: comsvcauth
    KC_SERVERURL: "https://loginproxy.gov.bc.ca/auth"

    SERVER_BODYLIMIT: 100mb
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"

    CACHE_DIR: "/var/lib/file-cache/data"
    CACHE_SIZE: 2GB
    CONVERTER_FACTORY_TIMEOUT: "60000"
    START_CARBONE: "true"
    UPLOAD_FIELD_NAME: template
    UPLOAD_FILE_COUNT: "1"
    UPLOAD_FILE_SIZE: 25MB

fluentBit:
  enabled: true
