{{ $kcSecretName := printf "%s-%s" (include "cdogs.fullname" .) "keycloak" }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "cdogs.fullname" . }}
  labels:
    {{- include "cdogs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    {{- include "cdogs.selectorLabels" . | nindent 4 }}
  strategy:
    resources: {}
    rollingParams:
      timeoutSeconds: 600
    type: Rolling
  template:
    metadata:
      labels: {{ include "cdogs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "cdogs.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.route.path }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.route.path }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: production
            {{- if .Values.config.configMap.KC_ENABLED }}
            - name: KC_CLIENTID
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "cdogs.configname" . }}-keycloak
            - name: KC_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "cdogs.configname" . }}-keycloak
            {{- end }}
            {{- if .Values.fluentBit.enabled }}
            - name: SERVER_LOGFILE
              value: /var/log/app.log
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "cdogs.configname" . }}-config
          volumeMounts:
            - name: file-cache-data
              mountPath: /var/lib/file-cache/data
            {{- if .Values.fluentBit.enabled }}
            - name: log-storage
              mountPath: /var/log
            {{- end }}
        {{- if .Values.fluentBit.enabled }}
        - name: fluent-bit
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.fluentBit.image.repository }}/{{ .Values.fluentBit.image.name }}:{{ .Values.fluentBit.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fluentBit.service.metrics.port }}
              name: {{ .Values.fluentBit.service.metrics.name }}
              protocol: TCP
            - containerPort: {{ .Values.fluentBit.service.httpPlugin.port }}
              name: {{ .Values.fluentBit.service.httpPlugin.name }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.fluentBit.route.metrics.path }}
              port: {{ .Values.fluentBit.service.metrics.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.fluentBit.route.metrics.path }}
              port: {{ .Values.fluentBit.service.metrics.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources: {{ toYaml .Values.fluentBit.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "cdogs.configname" . }}-aws
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "cdogs.configname" . }}-aws
            {{- if .Values.fluentBit.enabled }}
            - name: SERVER_LOGFILE
              value: /var/log/app.log
            {{- end }}
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: log-storage
              mountPath: /var/log
        {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: file-cache-data
        {{- if .Values.persistentVolumeClaim.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cdogs.configname" . }}-cache
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.fluentBit.enabled }}
        - name: log-storage
          emptyDir: {}
        - name: fluent-bit-config
          configMap:
            name: {{ include "cdogs.configname" . }}-fluent-bit
        {{- end }}
  test: false
  triggers:
    - type: ConfigChange
