{{- $kcSecretName := printf "%s-%s" (include "cdogs.configname" .) "keycloak" }}
{{- $kcSecret := (lookup "v1" "Secret" .Release.Namespace $kcSecretName ) }}
{{- if and (not $kcSecret) (and .Values.keycloakSecretOverride.password .Values.keycloakSecretOverride.username) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- if not .Values.config.releaseScoped }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- else }}
  labels: {{ include "cdogs.labels" . | nindent 4 }}
  {{- end }}
  name: {{ $kcSecretName }}
type: kubernetes.io/basic-auth
data:
  password: {{ .Values.keycloakSecretOverride.password | b64enc | quote }}
  username: {{ .Values.keycloakSecretOverride.username | b64enc | quote }}
{{- end }}
