# {{- $carboneSecretName := printf "%s-%s" (include "carbone.configname" .) "license" }}
# {{- $carboneSecret := (lookup "v1" "Secret" .Release.Namespace $carboneSecretName ) }}

# {{- if and (not $carboneSecret) (and .Values.carboneSecretOverride.license) }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   {{- if not .Values.config.releaseScoped }}
#   annotations:
#     "helm.sh/resource-policy": keep
#   {{- else }}
#   labels: {{ include "carbone.labels" . | nindent 4 }}
#   {{- end }}
#   name: {{ $carboneSecretName }}
# type: kubernetes.io/opaque
# stringData:
#   license: {{ .Values.carboneSecretOverride.license | b64enc | quote }}
# {{- end }}
