---
name: Docker Image CI
on:
  - push
  - pull_request
jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag common-document-generation-service:$(date +%s)
